### ISSUE TITLE
www.alojs.com looks hacked.

### ISSUE THREAD

**Issue by ismail-codar** [alojs/alo#133]
You can want to remove www.alojs.com. Also do not click it.

**Comment by katywings** [comment]
@ismail-codar Thank you for the important hint! I have to remove / update the domains in my projects :(... Couldnt pay for those domain subscriptions any longer as i am on low income at the moment...

**Comment by ismail-codar** [comment]
Thanks a lot. I wish you luck.

**Comment by katywings** [comment]
You too İsmail (@ismail-codar)! Keep up the good work 😊🙏
